"""Markdown report generator for scenario results."""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from shayde.core.scenario.models import (
    PartResult,
    ScenarioResult,
    StepResult,
    StepStatus,
)

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates Markdown reports from scenario results."""

    def __init__(self, results_dir: Path):
        self.results_dir = results_dir
        self.results: Optional[ScenarioResult] = None

    def load_results(self) -> ScenarioResult:
        """Load results from JSON file.

        Returns:
            ScenarioResult object

        Raises:
            FileNotFoundError: If results.json not found
            ValueError: If JSON is invalid
        """
        results_path = self.results_dir / "results.json"
        if not results_path.exists():
            raise FileNotFoundError(f"Results file not found: {results_path}")

        with open(results_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        self.results = self._parse_results(data)
        return self.results

    def _parse_results(self, data: dict) -> ScenarioResult:
        """Parse results from JSON data."""
        parts = []
        for part_data in data.get("parts", []):
            steps = []
            for step_data in part_data.get("steps", []):
                steps.append(StepResult(
                    step_id=step_data["id"],
                    desc=step_data["desc"],
                    status=StepStatus(step_data["status"]),
                    screenshot=Path(step_data["screenshot"]) if step_data.get("screenshot") else None,
                    duration_ms=step_data.get("duration_ms", 0),
                    error=step_data.get("error"),
                ))

            parts.append(PartResult(
                part=part_data["part"],
                title=part_data["title"],
                status=StepStatus(part_data["status"]),
                steps=steps,
            ))

        started_at = None
        if data.get("started_at"):
            started_at = datetime.fromisoformat(data["started_at"])

        completed_at = None
        if data.get("completed_at"):
            completed_at = datetime.fromisoformat(data["completed_at"])

        return ScenarioResult(
            scenario_id=data["scenario_id"],
            title=data["title"],
            status=StepStatus(data["status"]),
            parts=parts,
            started_at=started_at,
            completed_at=completed_at,
            output_dir=Path(data["output_dir"]) if data.get("output_dir") else None,
        )

    def generate(self, output_path: Optional[Path] = None) -> Path:
        """Generate Markdown report.

        Args:
            output_path: Output file path (defaults to report.md in results_dir)

        Returns:
            Path to generated report
        """
        if not self.results:
            self.load_results()

        if not output_path:
            output_path = self.results_dir / "report.md"

        content = self._generate_markdown()

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info(f"Report generated: {output_path}")
        return output_path

    def _generate_markdown(self) -> str:
        """Generate Markdown content."""
        r = self.results
        lines = []

        # Header
        status_emoji = self._get_status_emoji(r.status)
        lines.append(f"# {r.title} - 実行レポート\n")
        lines.append(f"**シナリオID**: {r.scenario_id}  ")
        if r.started_at:
            lines.append(f"**実行日時**: {r.started_at.strftime('%Y-%m-%d %H:%M:%S')}  ")
        lines.append(f"**所要時間**: {r.duration_ms / 1000:.1f}秒  ")
        lines.append(f"**結果**: {status_emoji} {r.status.value.upper()}\n")

        # Summary table
        lines.append("## サマリー\n")
        lines.append("| 項目 | 結果 |")
        lines.append("|------|------|")
        lines.append(f"| 総ステップ数 | {r.total_steps} |")
        lines.append(f"| 成功 | {r.passed_count} |")
        lines.append(f"| 失敗 | {r.failed_count} |")
        lines.append(f"| スキップ | {r.skipped_count} |")
        lines.append("")

        # Parts
        for part in r.parts:
            lines.extend(self._generate_part_section(part))

        # Footer
        lines.append("---\n")
        lines.append(f"*Generated by Shayde at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")

        return "\n".join(lines)

    def _generate_part_section(self, part: PartResult) -> list[str]:
        """Generate Markdown for a part."""
        lines = []
        status_emoji = self._get_status_emoji(part.status)

        lines.append(f"## Part {part.part}: {part.title} {status_emoji}\n")

        for step in part.steps:
            lines.extend(self._generate_step_section(step))

        lines.append("")
        return lines

    def _generate_step_section(self, step: StepResult) -> list[str]:
        """Generate Markdown for a step."""
        lines = []
        status_emoji = self._get_status_emoji(step.status)

        lines.append(f"### Step {step.step_id}: {step.desc}\n")
        lines.append(f"- **状態**: {status_emoji} {step.status.value}")
        lines.append(f"- **所要時間**: {step.duration_ms}ms")

        if step.error:
            lines.append(f"- **エラー**: `{step.error}`")

        # Screenshot
        if step.screenshot:
            # Make path relative to report
            rel_path = step.screenshot.name
            if step.screenshot.parent != self.results_dir:
                rel_path = str(step.screenshot.relative_to(self.results_dir))
            lines.append(f"\n![{step.desc}](./{rel_path})\n")

        # Assertions
        if step.assertions:
            lines.append("\n**検証結果**:")
            for assertion in step.assertions:
                icon = "✅" if assertion.passed else "❌"
                lines.append(f"- {icon} {assertion.type}: {assertion.message}")

        lines.append("")
        lines.append("---\n")
        return lines

    def _get_status_emoji(self, status: StepStatus) -> str:
        """Get emoji for status."""
        return {
            StepStatus.PASSED: "✅",
            StepStatus.FAILED: "❌",
            StepStatus.SKIPPED: "⏭️",
            StepStatus.PENDING: "⏳",
            StepStatus.RUNNING: "🔄",
        }.get(status, "❓")


def generate_report(results_dir: Path, output_path: Optional[Path] = None) -> Path:
    """Generate Markdown report from results directory.

    Args:
        results_dir: Directory containing results.json
        output_path: Output file path

    Returns:
        Path to generated report
    """
    generator = ReportGenerator(results_dir)
    return generator.generate(output_path)
